### ISSUE TITLE
Add our AS to the website

### ISSUE THREAD

**Issue by cookiemonster** [DIVD-NL/sites#121]
Let's add our scanning AS: 50.559, IP range: 194.5.73.1-254 to the website.

Ref: https://twitter.com/DIVDnl/status/1454036438992003073

**Comment by wschoot** [comment]
Anyone got a good idea about a location for this? I don't like yet another tile for this info. Maybe in the header? footer?

**Comment by therealprocyon** [comment]
Hmmmm there's not an about tile though and it could fit in an about page TBH

**Comment by cookiemonster** [comment]
Yes. In the footer would be fine.
