### ISSUE TITLE
Duplicate concent

### ISSUE THREAD

**Issue by wschoot** [DIVD-NL/sites#123]
we hebben duplicatie content in de site. DIVD.nl/reports geeft een identieke site als divd.nl/divd-nl/reports

Zal m ergens in de opbouw van de urls zitten. Dupe concent gaan zoekmachines niet goed op

**Comment by wschoot** [comment]
Voorbeeld:

```bash
$ curl -sq https://www.divd.nl/divd-nl/reports/ | md5sum
4798c2b2cccbf0b485a411aa94aff72f  -

$ curl -sq https://www.divd.nl/reports/ | md5sum
4798c2b2cccbf0b485a411aa94aff72f  -
```

**Comment by MrSeccubus** [comment]
Dit heeft waarschijnlijk te maken met de .htaccess files. De sites staan bij bit in 1 directory en de verschillende site names worden uit verschillende directories geserveerd.

**Comment by wschoot** [comment]
Ik denk dat we invloed hebben op het máken van de links. Wat ik bedoel is bijv de "Contact" link onderaan de partnerpagina. Die linkt naar https://www.divd.nl/divd-nl/partners/ en dat kan zonder "divd-nl". Dat pagina's óók via xxx/divd-nl/xxx bereikbaar zijn is niet zo'n issue zolang nergens die links worden gegenereerd.
