### ISSUE TITLE
Add our own Vulnerability Disclosure policy

### ISSUE THREAD

**Issue by cookiemonster** [DIVD-NL/sites#124]
- [ ] Add out VPD to (the footer) of the website: https://drive.google.com/file/d/1IsHVSHiB3U36nEL3ZKOoLxa7efKMegUS/view

**Comment by wschoot** [comment]
Ik heb momenteel geen toegang tot die file dus heb dat aangevraagd.

**Comment by wschoot** [comment]
Heb toegang -- deze file betreft een concept. Ik denk dat een final versie beter is.

**Comment by wschoot** [comment]
Staat inmiddels op https://www.divd.nl/security/ via zeroc0pter
