### ISSUE TITLE
Add donate w ERC-20 to donate page

### ISSUE THREAD

**Issue by cookiemonster** [DIVD-NL/sites#127]
DONATE VIA ERC-20
Prefer to donate with cryptocurrency?

**Cardano:** DdzFFzCqrhswAQ77W3ybUXvC5jTCgmAsnNa6YfiptSUhgEmniypKzzU1rSLZ9iAYorbt25WLtgv1ZG4qiEvnbMF9acm3TMTbUag9wWhX  

**Shiba Inu**: 0x2a44df7f3376906c644da3310360ca6311e752ba

Cardano icon:  https://cdn4.iconfinder.com/data/icons/crypto-currency-and-coin-2/256/cardano_ada-512.png
Shiba Inu icon:  https://www.flaticon.com/premium-icon/happy_2171981?term=shiba%20inu&page=1&position=18&page=1&position=18&related_id=2171981&origin=tag

Add between DONATE VIA PAYPAL and DONATE VIA PAYPAL.

**Comment by wschoot** [comment]
Supporten we ook BTC ? Dan kan dat er gelijk bij.
