### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by wschoot** [DIVD-NL/sites#133]
Right now we have a plain 404 page, better/nicer to  have a styled one

**Comment by therealprocyon** [comment]
A custom one uses 404.md

See:  https://jekyllrb.com/tutorials/custom-404-page/

**Comment by MrSeccubus** [comment]
zie: https://www.digitalocean.com/community/tutorials/how-to-create-a-custom-404-page-in-apache

**Comment by MrSeccubus** [comment]
Moet dus *en* in Jekyll voor lokale tests *en* in `.htacess` voor productie.

**Comment by therealprocyon** [comment]
Dit wordt/word(?) ook benoemd in de Jekyll documentation
