### ISSUE TITLE
New board members

### ISSUE THREAD

**Issue by cookiemonster** [DIVD-NL/sites#228]
On the first of April 2022, the following changes need to be made:

1. Change the content on https://www.divd.nl/contact/
2. Change the content on https://www.divd.nl/code/
3. Change the content  on https://www.divd.nl/team/ in the board section
4. Change the roles and descriptions of the old and new board members.

**Comment by wschoot** [comment]
@cookiemonster in preparation of this next month, where can one find a list of changes for this?
