### ISSUE TITLE
Onderzoeken of .fund bij de gewone repo ondergebracht kan worden. Wouter vraagt bij Frank na

### ISSUE THREAD

**Issue by wschoot** [DIVD-NL/sites#252]

**Comment by MrSeccubus** [comment]
Laten we in de basis voor 1 repo per site gaan. Dat is ook nodig als je een tool als forestry.io wilt gebruiken als headless cms. 

Www en CSIRT zijn een uitzondering omdat ze data delen maar als voor www een cms nodig zullen we die ook moeten splitsen.
