### ISSUE TITLE
Template for research cases typos

### ISSUE THREAD

**Issue by therealprocyon** [DIVD-NL/sites#35]
The template for research cases wrt researchers contains at least one typo

The template text for the researchers says `reseachers` instead of `researchers`

Not sure how easy this is to fix, as this applies to all cases AFAIK as well as the template itself.

**Comment by Lennaert89** [comment]
Not an issue relevant  to this PR

**Comment by therealprocyon** [comment]
It didn't have to do with this PR I thought, apologies.
